---
title: "D2SC ICMAs"
output: html_notebook
author: "Rex Harvilla"
date: "9-3-2026"
---


#ICMA 9-29-2026
```{r}
flights |> 
  ggplot(aes(x=dep_delay)) +
  geom_histogram()


```

```{r}
read_csv("week5-1_ClassData.csv")

```
#ICMA 9-24-2026
```{r}
billboard |> 
  pivot_longer(cols = starts_with("wk"),
               names_to = "week",
               names_prefix = "wk",
               values_to = "rank",
               values_drop_na = TRUE)
```

```{r}
billboard |> 
  separate(col = date.entered,
           into = c("year", "month", "day"),
           sep = 
             ) |> 
  unite(col = date.entered,
        year:day,
        sep = "-",
        remove=TRUE)
```

```{r}
billboard_long_dropna %>%
  pivot_wider(names_from = week,
              values_from - rank)
  


```

#ICMA 9-21-2026
```{r chnk-lbl, echo=TRUE}



```

```{r}
delay_summary <- flights |> 
  group_by(tailnum) |> 
  summarize(mean_delay = mean(arr_delay, na.rm = TRUE),
            n_flights = n())
```

#ICMA 9-17-2026
```{r}
flights |> 
  group_by(month) |> 
summarise(mean_delay = mean(arr_delay, na.rm = TRUE),
          sd_delay = sd(arr_delay, na.rm = TRUE),
          total_dep_delay = sum(dep_delay > 0, na.rm = TRUE),
          total_number = n()) |> 
  mutate(percentage = total_dep_delay/total_number)


```

```{r}
flights <- nycflights13::flights
glimpse(flights)

```

```{r}
flights |> 
  group_by(dest) |> 
  slice_max(arr_delay, n = 1) |>
  relocate(dest)
```

```{r}
flights |>
  group_by(month) |> 
  summarise(avg_delay = mean(dep_delay,
                             na.rm = TRUE)) |> round(2)
## mean doesnt silence missing data


```

```{r}
flights |> 
  mutate(speed=distance/air_time * 60,
         .after = distance) |> 
  select(year, month, day, dep_time, air_time, distance, how_fast=speed)


```

```{r}
flights |> 
  relocate(carrier,
           .after = day)


```

```{r}
flights |> 
  rename(dep_airport = origin)


```





#ICMA 9-15-2026
```{r}
flights |> 
  filter(arr_delay > 120 & dep_delay <= 0) |> arrange(desc(arr_delay))

```

```{r}
PlantGrowth |>
  ggplot(aes(y=weight, x=group)) +
  geom_boxplot(width = 0.2)

```

```{r}
flights |>
         glipmse()
```



```{r}
#| label: setup
#| include: false
#| echo: true

library("tidyverse")
library("palmerpenguins")
library("nycflights13")

```
# ICMA 9-10-2026

```{r}
ggplot(data=penguins, mapping=aes(x=flipper_length_mm,
                                  y=bill_length_mm)) + 
  geom_point()
```

```{r}
PlantGrowth
ggplot(data=PlantGrowth, mapping=aes(y=weight,x=group)) + 
  geom_point(alpha=0.5) + stat_summary(geom="pointrange",fun.data = "mean_se", color="purple")
```
that sure is tidy data


# ICMA 9-3-2026

```{r}
plot(cars)
```
In the plot, I see a graph with the x axis being speed and going from 0 to 25, and the y axis showing distance and going from 0 to 100. I see points plotted on the graph in a upward trend. I see my reflection in my computer screen with a big smile on my face because yippee!!! time for R!!!!

